### ISSUE TITLE
Bug: CloudWatch log name is not parsing correctly

### ISSUE THREAD

**Issue by Derek-X-Wang** [domagojk/serverless-console#31]
doesn't seem it parse the name correctly from serverless.yml

![Screen Shot 2020-09-04 at 2 12 49 AM](https://user-images.githubusercontent.com/6364170/92222768-593c2980-ee54-11ea-9ca0-24a40556dfa9.png)
![Screen Shot 2020-09-04 at 2 13 40 AM](https://user-images.githubusercontent.com/6364170/92222774-5c371a00-ee54-11ea-9375-07231d31fdb9.png)

the correct name shall be `rtc-service-dev-websocket-heartbeat` in my case

**Comment by domagojk** [comment]
@Derek-X-Wang Thanks for reporting! This should be fixed in ver 0.7.1

**Comment by domagojk** [comment]
There was an error in ver 0.7.1. It should now work in 0.7.2

**Comment by Derek-X-Wang** [comment]
it works. thx a lot

**Comment by Derek-X-Wang** [comment]
![Screen Shot 2020-09-12 at 1 52 44 AM](https://user-images.githubusercontent.com/6364170/92991813-13f2aa00-f49b-11ea-9ae1-c636eb255a98.png)
![Screen Shot 2020-09-12 at 1 52 57 AM](https://user-images.githubusercontent.com/6364170/92991840-253bb680-f49b-11ea-829c-26636827b5fa.png)

another parse issue :) @domagojk

**Comment by domagojk** [comment]
@Derek-X-Wang What would be a correct name in that case?
The extension now resolves it as expected (just as in the first example you posted): `${serviceName}-${stage}-${functionName}`

**Comment by icaptnbob** [comment]
This extension is failing to find prod Cloud logs but works for dev stage. It was working at the end of August. Nothing has changed in the serverless.yml file since then. 
I keep getting this message when I go to the prod stage of any lambda function: "The specified log group does not exist."
The dev stage shows the current logs.

The prod stage logs are visible in AWS Cloudwatch for all of these.

This seems to coincide with this extension change. Is there anything I can do to debug?

**Comment by domagojk** [comment]
I had to revert the extension to 0.7.0 since this fix obviously wasn't implemented correctly. I suspect this also has to do with serverless framework version.
@icaptnbob Can you please copy/paste your function definition from serverless.yml and also provide a serverless framework version you are using and I will try to debug the issue.

**Comment by icaptnbob** [comment]
Hi Domagojk. Thanks for the very quick response.

Is this what you want?

npm list -depth 0
+-- serverless-bundle@1.4.0
+-- serverless-pseudo-parameters@2.5.0

serverless.yml (extract)
service: transact-drivers

plugins:
    - serverless-bundle
    - serverless-pseudo-parameters

custom:
    stage: ${opt:stage, self:provider.stage}
    resourcesStages:
        prod: prod
        dev: dev
    resourcesStage: ${self:custom.resourcesStages.${self:custom.stage}, self:custom.resourcesStages.dev}

provider:
    name: aws
    runtime: nodejs12.x
    stage: ${opt:stage, 'dev'}
    region: eu-central-1

functions:
    # Driver Lambdas
    movacash-driver:
        handler: src/driver/movacash-driver.main
        vpc: ${self:custom.vpc}

    ecw-driver:
        handler: src/driver/ecw-driver.main
        vpc: ${self:custom.vpc}

    # Drivers Api
    list_driver:
        handler: src/driver/controller.listDriver
        events:
            - http:
                  path: driver/{driverName}
                  method: get
                  private: true

    list_drivers:
        handler: src/driver/controller.listDrivers
        events:
            - http:
                  path: driver
                  method: get
                  private: true

    driver_post:
        handler: src/driver/controller.executeDriverPost
        events:
            - http:
                  path: execute/{action} 
                  method: post
                  private: true

**Comment by Derek-X-Wang** [comment]
Hi @domagojk, the correct name will be

**postConfirmation-dev**

for the name, there are two cases

1. default name, if the name field is not provided.
2. name filed is provided.

@icaptnbob using the default name and I use the explicit name.

for my case, 
stage is `dev`
service name is `user-service`
stackName is ${self:service}-${self:provider.stage} => `user-service-dev`

`name: postConfirmation-${self:provider.stage}` => `postConfirmation-dev`
`name: ${self:provider.stackName}-user-get` => `user-service-dev-user-get`

**Comment by domagojk** [comment]
Thanks, @icaptnbob that's it 👍 

@Derek-X-Wang The problem is that I can't easily determine whether the explicit or implicit name is used (since `sls print` always shows as it was explicit). And also I can't just use explicit names since it should work for multiple stages which rely on `${serviceName}-${stage}-${functionName}` format. The only way I could use that is to execute `sls print` for every stage (also related to #10).

**Comment by Derek-X-Wang** [comment]
@domagojk Here is the snippet of my sls print

so my difference with icaptnbob is I have `name` field

so if the name field exists. that shall be used as the log name and lambda name. if that is not present, that will be the default name.
```
functions:
  postCreateHandler:
    handler: src/post.create
    name: content-service-dev-post-create
    tags:
      rest: mobz post api
    vpc:
      securityGroupIds:
        - Ref: LambdaSecurityGroup
      subnetIds:
        'Fn::Split':
          - ','
          - 'Fn::ImportValue': dev-private-subnets
    events: []
  postUpdateHandler:
    handler: src/post.update
    name: content-service-dev-post-update
    tags:
      rest: mobz post api
    vpc:
      securityGroupIds:
        - Ref: LambdaSecurityGroup
      subnetIds:
        'Fn::Split':
          - ','
          - 'Fn::ImportValue': dev-private-subnets
    events: []
```
