### ISSUE TITLE
 The specified log group does not exist.

### ISSUE THREAD

**Issue by vatsenko** [domagojk/serverless-console#45]
Hi, 

My serverless.yml

```
service: aws
app: exact
org: degunfactor
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs14.x
  profile: degunfactor
  lambdaHashingVersion: 20201221
  stage: v2
  region: eu-central-1
...
functions:
  hello:
    handler: handler.handshake
    name: hello
    events:
     - http:
        method: any
        path: hello
        cors: true
        integration: lambda-proxy
```

I have log groups in Cloudwatch under eu-central-1 - /aws/lambda/hello - and logs under this group and also this folder visible in Logs Insights.

im able to see the logs when I add log groups manually (Source Custom, Select Region and choose the log group from dropdown)

I see all my functions when I add service as a Source -Serverless Framework, however no logs under the functions and the message is "The specified log group does not exist".

<img width="1671" alt="Screenshot 2021-10-01 at 13 00 27" src="https://user-images.githubusercontent.com/6514188/135602058-605d2080-0311-4f20-8946-14933de9ef14.png">
